// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireExp

import (
	"wireExp/internal/api/handler"
	"wireExp/internal/api/repository"
	"wireExp/internal/api/router"
	"wireExp/internal/api/service"
	"wireExp/internal/clients"
)

// Injectors from wire.go:

func NewServer() *Server {
	db := clients.NewExpDB()
	userRepo := repository.NewUserRepo(db)
	userService := service.NewUserService(userRepo)
	userHandler := handler.NewUserHandler(userService)
	routerRouter := router.NewRouter(userHandler)
	server := &Server{
		Router: routerRouter,
	}
	return server
}

// wire.go:

type Server struct {
	Router *router.Router
}
